name: Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1
        with:
          fetch-all: true

      - name: Test
        run: |
          pnpm test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
